services:
  pcap-broker:
    build: .
    container_name: pcap-broker
    restart: always
    environment:
      PCAP_COMMAND: |-
        tcpdump -U --immediate-mode -ni kmob0 -s 65535 -w - portrange 9000-9999

      LISTEN_ADDRESS: "0.0.0.0:65000"
    network_mode: host
